name = "gsv"
version = "1.4.0"
gleam = ">= 0.32.0"
description = "A simple csv parser and generator written in gleam "

licences = ["Apache-2.0"]
repository = { type = "github", user = "bcpeinhardt", repo = "gsv" }

internal_modules = [
  "gsv/internal",
  "gsv/internal/*",
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
