name = "gsv"
version = "2.0.3"
gleam = ">= 0.32.0"
description = "A simple csv parser and generator written in gleam "

licences = ["Apache-2.0"]
repository = { type = "github", user = "bcpeinhardt", repo = "gsv" }

internal_modules = [
  "gsv/internal",
  "gsv/internal/*",
]

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
birdie = ">= 1.2.3 and < 2.0.0"
